name: AWS-GitHub-Sync

on:
  push:
    branchs: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  ListS3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # install AWS cli
      - uses: unfor19/install-aws-cli-action@v1

      # assume role
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::726086112472:role/GitHub_Actions_Role

      - name: List S3 Buckets
        run: |
          echo "==============>>>> All S3 Buckets"
          aws s3 ls