name: AWS-GitHub-Sync

on:
  push:
    branches: ["proto-two"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the code repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # assume role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::726086112472:role/GitHub_Actions_Role

      - name: Sync to S3
        run: aws s3 sync . s3://amazon-cloudfront-secure-static-site--s3bucketroot-gs8mq3etvr3h/ --exclude ".git/*" --exclude ".DS_Store" --exclude ".venv/*"